-- ============================================================
-- Audit Log: Enforce Append-Only at the Database Level
-- ============================================================
-- Run these statements manually as a superuser AFTER the
-- initial prisma db push / migrate deploy.
--
-- They revoke UPDATE and DELETE privileges on audit_log from
-- the application DB user, ensuring no code path (even a
-- future bug or compromised dependency) can alter audit rows.
--
-- Replace 'app_user' with your actual PostgreSQL role name
-- (the user in DATABASE_URL).
-- ============================================================

-- Revoke destructive operations from the app user
REVOKE UPDATE, DELETE ON TABLE "AuditLog" FROM app_user;

-- Verify: the following should list only SELECT and INSERT
-- SELECT privilege_type FROM information_schema.role_table_grants
-- WHERE table_name = 'AuditLog' AND grantee = 'app_user';

-- ============================================================
-- Optional: hash-chain trigger for tamper-evidence
-- If you want each row to hash the previous row's hash:
--
-- CREATE OR REPLACE FUNCTION audit_log_hash_chain()
-- RETURNS TRIGGER AS $$
-- DECLARE
--   prev_hash TEXT;
-- BEGIN
--   SELECT row_hash INTO prev_hash
--   FROM "AuditLog" ORDER BY timestamp DESC LIMIT 1;
--   NEW.prev_hash := COALESCE(prev_hash, '');
--   NEW.row_hash := encode(
--     digest(NEW.prev_hash || NEW.timestamp::text || NEW."actorName" ||
--            NEW.action || NEW."entityType" || COALESCE(NEW.changes::text, ''), 'sha256'),
--     'hex'
--   );
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;
--
-- CREATE TRIGGER audit_log_hash_chain_trigger
-- BEFORE INSERT ON "AuditLog"
-- FOR EACH ROW EXECUTE FUNCTION audit_log_hash_chain();
-- ============================================================
